---
driver:
  name: docker
  # binary: "./docker"
  socket: tcp://docker.chefbrigade.io:443
  tls_verify: true
  tls_cacert: test/docker/docker.ca
  tls_cert: test/docker/docker.pem
  tls_key: test/docker/docker.key

suites:
- name: default
  run_list:
  - recipe[bsdcpio]

platforms:
  - name: ubuntu-14.04
